// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaidTraffic.Api.Persistence;

#nullable disable

namespace PaidTraffic.Api.Persistence.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    [Migration("20260919102301_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaidTraffic.Api.Persistence.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("IncidentId", "Id");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Campaign", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Conversions")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PermanentFailure")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<decimal>("Spend")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransientFailuresRemaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", t =>
                        {
                            t.HasCheckConstraint("CK_Campaign_Performance", "\"Spend\" >= 0 AND \"Conversions\" >= 0 AND \"Revenue\" >= 0");
                        });
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Conversions")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<decimal>("Spend")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<bool>("Violated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("CampaignId", "PolicyId", "WindowStart", "WindowEnd")
                        .IsUnique();

                    b.ToTable("Evaluations", t =>
                        {
                            t.HasCheckConstraint("CK_Evaluation_Window", "\"WindowStart\" < \"WindowEnd\"");
                        });
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('PendingApproval', 'Executing', 'ExecutionFailed')");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "Id");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.OperationalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .IsUnique();

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("MaxSpendWithoutConversion")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<decimal?>("MinimumRoas")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<decimal>("MinimumSpendForRoas")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("Policies", t =>
                        {
                            t.HasCheckConstraint("CK_Policy_Thresholds", "\"MaxSpendWithoutConversion\" > 0 AND (\"MinimumRoas\" IS NULL OR \"MinimumRoas\" > 0) AND \"MinimumSpendForRoas\" >= 0");
                        });
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.AuditEntry", b =>
                {
                    b.HasOne("PaidTraffic.Api.Persistence.OperationalAction", null)
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaidTraffic.Api.Persistence.Evaluation", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaidTraffic.Api.Persistence.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Evaluation", b =>
                {
                    b.HasOne("PaidTraffic.Api.Persistence.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Incident", b =>
                {
                    b.HasOne("PaidTraffic.Api.Persistence.Evaluation", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.OperationalAction", b =>
                {
                    b.HasOne("PaidTraffic.Api.Persistence.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PaidTraffic.Api.Persistence.Policy", b =>
                {
                    b.HasOne("PaidTraffic.Api.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
